### ISSUE TITLE
🚧Add checks only option to release targets

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#106]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, all targets first run a list of checks before the actual target executes.  If all of these checks return true which means that the check was successful, then the target will run.  The release targets _**Preview**_ and _**Production**_ both do this as well.  The problem is that there is a use case for the purpose of debugging to only run the checks without executing the actual target.

An example of this would be wanting to dry-run the release targets locally to verify that everything checks out first without performing the actual release.  This feature would accomplish this.

---

### **What to implement:**
Add a build parameter with the name ~~`--checks-only`~~ `--release-checks-only`.   ~~This will require a NUKE parameter with a property with a getter and a setter with a backing field.  The reason for the full prop instead of the auto prop is due to needing to have the setter execute to check that a parameter has been used in the CLI command.  If the setter is being executed, this means that the CLI command switch was used.  At this point, the getter should flip a flag that can be used by the targets to see if the target should execute.~~

### **Refer to the use cases below:**

1. To run the checks _**AND**_ execute the target:
    - Do not use the switch
      - Example: `dotnet cicd PreviewRelease`
2. To run the checks _**ONLY**_ and _**NOT**_ execute the target
    - Use the switch
      - ~~Example: `dotnet cicd PreviewRelease --checks-only~~
      - Example: `dotnet cicd PreviewRelease --release-checks-only`

### Acceptance Criteria

- [x] New command parameter added to the project.
- [x] All targets that contain an execute implementation should check for execution
- [x] All targets that use the option, should print a warning to the console that the target is being skipped.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Changed the required switch name from `--checks-only` to `--release-checks-only`
