### ISSUE TITLE
🚧Add nuget package tags

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#107]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

For the NuGet package, add package tags that will help with people search for the NuGet package.

This can be accomplished by adding the XML element named `<PackageTags></PackageTags>` to the _**csproj**_ file.
For the element content, add space-delimited keywords that would help people find the package.

The aim is to help not only with regular package search but also with finding it in the context of a dotnet tool using the command `dotnet tool search <search-term>` command.

**Add the keywords:**
- cicd
- build
- ci
- cd
- status-checks

This would end in a result of `<PackageTags>cicd build ci status-checks cd</PackageTags>`

**Location to add the tag:**
Add to the _**Velaptor.csproj**_ file
```diff
    <ApplicationIcon>cicd-logo.ico</ApplicationIcon>
    <PackageId>KinsonDigital.CICD</PackageId>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Authors>Calvin Wilkinson</Authors>
    <Company>Kinson Digital</Company>
    <Product>CICD</Product>
    <Description>CICD application for running builds, tests, and status checks for the KinsonDigital organization projects.</Description>
    <Copyright>Copyright ©2022 Kinson Digital</Copyright>
+   <PackageTags>cicd build ci status-checks cd</PackageTags>
    <Configurations>Debug;Release</Configurations>
    <PackageIcon>cicd-logo-dark-mode.png</PackageIcon>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>cicd</ToolCommandName>

```

### Acceptance Criteria

- [ ] Package tags XML element with keywords added to the _**csproj**_ file.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
