### ISSUE TITLE
🚧Improve generation of local secrets file

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#108]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

**Issue 1:**
When generating the local secrets file, set the default value of the single key added to the JSON file to a value of _**GitHubApiToken**_.  Currently, when the file is generated for the first time, both the key and the value are empty.

When setting up a new project, the exact name of the "Key" value for the GitHub API token is not always remembered, so the default value will help with this and make it a bit simpler to set up.

**Issue 2:**
Also, when setting up a new project with _**CICD**_ for the first time, it is common to forget that after installing the dotnet tool, the _**local-secrets.json**_ file MUST exist in the _**.github**_ folder to run _**CICD**_ locally.  This is because `IHttpClientFactory` depends on it.  To fix this, check if the file exists and if it does not, automatically create it.

**Error Produced:**
<img width="820" alt="image" src="https://user-images.githubusercontent.com/85414302/207569534-7d71ef71-1a00-4997-b415-52efa1c1b847.png">

### Acceptance Criteria

- [x] Default key value set to _**GitHubApiToken**_ when the file is first generated.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
