### ISSUE TITLE
🚧Improve logging with incorrect PR number

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#109]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When invoking the `ThatThePullRequestExists()` requirement method with an invalid PR number, the error thrown does not contain any informative information other than something that went wrong.  Improve the error logged to the console so it is more obvious what went wrong.

**Example Of Informative Error:**
<img width="483" alt="image" src="https://user-images.githubusercontent.com/85414302/195951950-5e4166a7-848f-4366-beb2-07b7f85dc017.png">

This was invoked by using the command `dotnet cicd PreviewFeaturePRStatusCheck --pull-request-number 400`
Just make sure that the PR number does not exist.

### Acceptance Criteria

- [x] More informative error logged to the console when using non-existing PR numbers

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
