### ISSUE TITLE
🚧Change auto parameters file generation

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#110]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, when the build system generates the `parameters.json` file, it does not have an extra line at the end of the file.  This ends up being flagged in GitHub reviews as needing to have at least one extra line.

Change the file generation process so that their is an extra line at the end of the file.

### Acceptance Criteria

- [ ] Extra line is at the end of the `parameters.json` file when it is generated.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes

**Reason:**
This is because the `parameters.json` file is generated by NUKE.  We do not have control over the creation of this file.
