### ISSUE TITLE
🚧Release PR status checks not working correctly

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#113]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

While executing a preview release PR status check for **_Velaptor_**, the status check reported that milestone _**v1.0.0-preview.10**_ did not contain a single release todo issue.

This was not the case.  The milestone did indeed contain a release todo issue.  Investigation revealed that there is a bug in the project.

The bug is located in the _**ExtensionsMethods.cs**_ file in the `IsReleaseToDoIssue()` extension method.
Refer to the code block below to implement the fix.

```diff
    public static bool IsReleaseToDoIssue(this Issue issue, ReleaseType releaseType)
    {
        var releaseLabelOrTitle = releaseType switch
        {
            ReleaseType.Preview => "🚀Preview Release",
            ReleaseType.Production => "🚀Production Release",
            ReleaseType.HotFix => "🚀Hot Fix Release",
            _ => throw new ArgumentOutOfRangeException(nameof(releaseType), releaseType, null),
        };

-       var isIssue = issue.IsPullRequest();
+       var isIssue = issue.IsPullRequest() is false;
        var validTitle = issue.Title == releaseLabelOrTitle;
        var validLabelType = issue.Labels.Any(l => l.Name == releaseLabelOrTitle);

        return isIssue && validTitle && validLabelType;
    }
```

### Acceptance Criteria

- [x] Bug fixed with extension `IsReleaseToDoIssue()` method

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
