### ISSUE TITLE
🚧Handle tag protection rules

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#117]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

If a project contains a tag protection rule and a release is created, an `ApiValidationException` exception is thrown.  This caused a major issue in not knowing why a preview release was failing for **Velaptor** because there was a tag protection rule on the project and during the creation of the release which creates a tag, this error was thrown.  

Unfortunately, the error was not being caught very well and vital information on what was going on was not visible.
If this exception is handled correctly then the information from the exception could be logged correctly to make it easier to find out why a workflow is failing.

The only area where this would become and issue is when creating a GitHub release when running the release targets.
This is where you should add the check and log the message.

Create an extension method to quickly parse out the data from the exception and turn it into readable string data.  This data is what can then be logged into the GitHub console.

The valuable information from the exception is below:
```cs
ApiValidationException.apiEx.Message
ApiValidationException.apiEx.StatusCode
ApiValidationException.ApiError.Errors.Code
ApiValidationException.ApiError.Errors.Field
ApiValidationException.ApiError.Errors.Message
ApiValidationException.ApiError.Errors.Resource
```

### Acceptance Criteria

- [x] Extension method created to create readable error info from the `ApiValidationException`
- [x] Handle the `ApiValidationException` throughout areas of the code base where data would be changed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
