### ISSUE TITLE
🚧Improve release tweet process

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#118]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When running a preview or production release, it can perform a tweet of the release.  This tweet process can be skipped.  But unfortunately, nothing is being logged to the console that the tweet was skipped, that the tweet template does not exist, or if it does exist that it was empty or longer than the valid amount that you are allowed to tweet.  All of these improvements and checks need to be implemented.

If some of the checks end up with a tweet not being performed, log a message but do not fail the build.  This is because the tweet can only occur after everything has been released.  

Create a new service called `LoggingService` that can encapsulate all of the `Serilog` functionality.  This can then be injected into other services for use.  Example:  This will be injected into a new tweet service.

All of the current and new functionality should be added to a new service named `TweetService`.
Once the service is created, refactor the tweet code to use the service instead.

**Tweet Improvements:**

1. If a release tweet was set to be skipped, perform a regular log that the tweet was skipped.
2. If the tweet was not set to be skipped, but a tweet template does not exist, log a warning that the tweet template does not exist.
   - Do not fail the build
4. If the tweet template does exist but is empty, log a warning that the tweet was empty.
    - Do not fail the build
5. If the tweet template does exist but is longer than the tweet limits, log a warning that the tweet is too large.
    - Do not fail the build

### Acceptance Criteria

- [x] Create a new logger service named `LoggingService`.
  - This will use the `Serilog` logging calls to log into the console.
- [x] Create a new service called `TweetService`
  - `LoggingService` will be injected into this service
- [x] Info message logged if the tweet is set to be skipped
- [x] Log warning if a tweet template does not exist.
  - Perform the log inside of this service
  - Do not fail the build
- [x] Log a warning If the tweet template content is empty
  - Perform the log inside of this service
  - Do not fail the build
- [x] ~Log a warning if the tweet template content is longer than the tweet limits~
  - ~Perform the log inside of this service~
  - ~Do not fail the build~

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Did not implement the feature about tweet length with the AC item below.

- [x] ~Log a warning if the tweet template content is longer than the tweet limits~
  - ~Perform the log inside of this service~
  - ~Do not fail the build~

**Reason:**
It was discovered that tweet length is more complicated than just text length.  Other things are taken into account such as emojis, different languages, and URL processing.

It would be more complicated than it is worth to implement this.
