### ISSUE TITLE
🚧Setup QA testing issues to be ignored in milestones

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#119]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When a QA testing issue is in the milestone while a **Preview Release PR Status Check** or **Production Release PR Status Check** is running, the status check fails because it notices that the QA Testing issue is not contained in the release notes.

This type of issue needs to be detected as a **QA Testing** type of issue and ignored when analyzing the release notes.

This setup should be very simular to the ignoring of the release todo issue and PR types.

### Acceptance Criteria

- [ ] QA Testing type issues ignored when in a milestone.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
