### ISSUE TITLE
🚧Update README

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#12]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the README file by changing the NOTICE!! section.  
This section should be changed to explain that this project is for the KinsonDigital organization and is only maintained by the organizational members themselves.

Explain that we will not be taking outside contributions, but feature requests and bug reports are welcome.

![image](https://user-images.githubusercontent.com/85414302/192094578-0b45dd9d-4d3c-43ed-a070-7ee482ba3b14.png)

### Acceptance Criteria

- [x] README file updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
