### ISSUE TITLE
🚧Add README pre-processing feature

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#121]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a feature to the CICD system that allows the ability to pre-process README files for preparation for rendering on nuget.org when a NuGet package contains a README file.

### **Reason:**
The reason is that not all HTML in markdown is supported by other systems. One system where it is supported is GitHub.  A system that is not supported is on the nuget.org website.  Due to this, the readme file should have some pre-processing performed before packing it into the package.

Instead of doing this manually, it is much better to automate this.

### **Settings:**
The setup for this should be a NUKE parameter in the `settings.json` file in the `.nuke` directory.
The parameter should be a `boolean` type value with the name `PreProcessReadMe`.
The default value should be a value of `false`.  If the parameter is not defined in the file, then it should be a value of `false`.

### **Example File:**
```json
{
  "$schema": "./build.schema.json",
  "Solution": "CICD.sln",
  "RepoOwner": "KinsonDigital",
  "RepoName": "CICD",
  "ProjectName": "CICD",
  "PreProcessReadMe": false
}
```
> **Note**
> A boolean value should be supported by NUKE.  If this is an issue, then use a string value of `"true"` or `"false"`
> and see if that will work.

> **Note**
The README file should have markdown comments that signal the start and ending sections that should be commented on or uncommented in the markdown.  A **comment section** signifies what is going to be commented out during processing and an **uncomment section** signifies what is going to be uncommented during processing.

> **Warning**
 Fail the build if the pre-processing syntax is invalid or fails if anything goes wrong. The reason for this is that if the build does not fail on bad processing, then the NuGet package will be published with a bad README file.  This cannot be allowed. 
 A high level of testing and checks must be performed to reduce the chance of this occurring.  Any failures during processing should have clear and understandable logs/exceptions to make it easy to find out what is going wrong.

Below is the pre-processing syntax:

**Comment Sections:**
- Comment section start: `<!--PRE-PROCESSING-COMMENT-START-->`
- Comment section stop: `<!--PRE-PROCESSING-COMMENT-STOP-->`

**Uncomment Sections:**
- Uncomment section start: `<!-- PRE-PROCESSING-UNCOMMENT-START-->`
- Uncomment section stop: `<!--PRE-PROCESSING-UNCOMMENT-STOP-->`

**Processing Checks:**
- Make sure that a start also has a stop.  If matching pairs do not exist, then fail the build.
- The text must be EXACT between the `<!--` and `-->` comment signifiers.  If not, fail the build.
- A start and stop cannot be on the same line.  If they are, fail the build.
- There must not be any other content on the same line of text as a start or stop.  if so, fail the build.

### Acceptance Criteria

- [x] Pre-processing parameter/setting implemented
- [x] Comment processing works
- [x] Uncomment processing works
- [x] Full live testing against the **CICDTest** project performed.
- [x] Manual publish process performed in nuget.org to verify how README looks.
- [x] Setup project README to have pre-processing syntax

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Moved this issue from release _**v1.0.0-preview.13**_ to _**v1.0.0-preview.14**_.
