### ISSUE TITLE
🚧Adjust workflow templates to restore dotnet tools

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#13]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, all of the workflow templates that can be generated for a project do not include a job step to restore the dotnet tool.  Fix this by updating all of the workflow templates to include that extra step.

**Workflow Changes:**
```diff
name: ✅Build Status Check


+defaults:
+  run:
+    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - preview/v*.*.*-preview.*
      - release/v*.*.*
      - master


jobs:
  build_project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
+    - name: Restore DotNet Tools
+      run: dotnet tool restore
    - name: Run Build Status Check
      run: dotnet cicd BuildStatusCheck
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Acceptance Criteria

- [x] `build-status-check.yml`
- [x] `feature-pr-status-check.yml`
- [x] `hotfix-pr-status-check.yml`
- [x] `prev-feature-pr-status-check.yml`
- [x] `prev-release-pr-status-check.yml`
- [x] `prev-release.yml`
- [x] `prod-release-pr-status-check.yml`
- [x] `prod-release.yml`

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
