### ISSUE TITLE
🚧Change how assigned issues are checked

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#138]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

There was an issue where the web interface had an assignee added but the object in code was returning the **Assignees** array with a single item and the **Assignee** property as null.  

CICD uses the **Assignee** property to check if the issue has been assigned, not the **Assignees** property.  The issue was resolved by unassigning the current assignee and then reassigning the same assignee back again.  This ended up changing the **Assignee** property to not null.

To make sure this does not happen again, check both the **Assignee** property and **Assignees** array property if the user exists.

Look in the `ThatAllMilestoneItemsAreAssigned()` requirement method for this change.  Also look throughout the rest of code base for any assignment related code and update that as well.

### Acceptance Criteria

- [x] Checking for issue assignment updated.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
