### ISSUE TITLE
🚧Fix issue with preview releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#139]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fixed an issue where the preview release is crashing due to incorrect version string construction.

This is occurring due to a bug that was introduced into the previous release _**v1.0.0-preview.15**_.
The fix is simple.  

Go into the  **CICD.Release.Preview** file and in the **PreviewRelease** target execution section, on line 58, add logic to check if the version string starts with the letter 'v', and if it does not, add one.

```diff
- var version = projectService.GetVersion();
+ version = version.StartsWith('v') ? version : $"v{version}";
```

### Acceptance Criteria

- [x] Preview release issue fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
