### ISSUE TITLE
🚧Fix bug with twitter announcements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#144]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a bug when skipping twitter announcements.  When trying to skip announcements, a null reference exception is thrown by NUKE itself with no other information.  

The reason this is occurring is that the `SkipTwitterAnnouncement` NUKE parameter does not have a property getter.  During the processing of the property, while NUKE is loading, the reflection does not find the property because it does not have the getter.  This then causes an exception.  The issue is that the exception contains no further information.

It could contain an inner exception but the exception cannot be caught inside of the IDE to see if the exception contains an inner exception.

The fix is simple, add a getter to the NUKE parameter property `SkipTwitterAnnouncement`

### Acceptance Criteria

- [x] A getter has been added to the `SkipTwitterAnnouncement` property in the **CICD.cs** file.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
