### ISSUE TITLE
🚧Change owner and repos name setup

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#15]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Convert the 'Owner' and 'MainProjName` fields to private properties that are marked as a NUKE `[Parameter]`.
Refactor the name of the 'Owner` field (which is being converted into a prop) to `RepoOwner`.
Refactor the name of the `MainProjName` field (which is being converted into a prop) to `RepoName`.

Also, add the correct parameters and values in the `~/.nuke/parametes.json` file like below.

```json
{
  "$schema": "./build.schema.json",
  "Solution": "CICD.sln",
  "RepoOwner": "KinsonDigital",
  "RepoName": "CICD"
}
```

### Acceptance Criteria

- [x] Refactor the `Owner` field name to `RepoOwner` and refactor to a `private` property
- [x] Refactor the `MainProjName` field name to `RepoName` and refactor to a `private` property

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
This is set to https://github.com/KinsonDigital/CICD/labels/%E2%9C%A8new%20feature because it is allowing the ability to externally set the `RepoOwner` and `RepoName` externally in the `.nuke/parameters.json` file.  This allows other projects to choose what those values are and makes the build system more flexible.
