### ISSUE TITLE
🚧Update workflow generation

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#151]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the workflow generation process by updating the version of the **checkout** action from _**v2**_ to _**v3**_.

**Reason:**
GitHub is moving away from **Node v12** to **Node v16**.  Due to this change, GitHub is updating all of its actions to support **Node v16** which is part of the process of moving away from _**Node v12**_.  

More info [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

**What To Do:**
Go into all of the workflow templates and update the version from _**v2**_ to _**v3**_.
They can all be found in the **_./CICD/WorkflowTemplates_** folder.

**The Change:**
```diff
- actions/checkout@v2
+ actions/checkout@v3
```

### Acceptance Criteria

- [x] All workflow templates updated to use the checkout action _**v3**_
- [x] Update the checkout action in the _**./.github/workflows/preview-release.yml**_ file

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by kselena** [comment]
Issue not closed when PR was merged.  Closing now.
