### ISSUE TITLE
🚧Add code coverage parameter

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#153]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability to create code coverage reports in a particular directory when running unit tests.

This should be done by creating new NUKE parameters.
Create a parameter named `produce-coverage-report`.  This will be a `bool` parameter that will have a default value of `false`.  This is what will produce the coverage report if the `true`.

The other parameter will be named `coverage-report-directory`.  This will be the directory path where the coverage report will be saved.  The default value will be an empty string.  If not set, then this will use the default location.  This parameter will not be used unless the `produce-coverage-report` parameter is set to a value of `true`

### Acceptance Criteria

- [ ] A new parameter named `produce-coverage-report` created
    - [ ] Default value is `false`
    - [ ] Has a description of the parameter that can been seen when using the `dotnet cicd --help` command
- [ ] A new parameter named `coverage-report-directory` created
    - [ ] Default value is an empty string
    - [ ] Not used or taken into account if the `produce-coverage-report` parameter is set to a value of `false`
    - [ ] Has a description of the parameter that can been seen when using the `dotnet cicd --help` command

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
> **Note** Moved from the **_v1.0.0-preview.18_** milestone to the **_v1.0.0-preview.19_** milestone

**Comment by CalvinWilkinson** [comment]
Closed

**Reason:** This is not being used anymore
