### ISSUE TITLE
🚧Update workflow templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#154]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the workflow templates to use env files instead of the `set-output` command.
This is getting deprecated by GitHub and will be disabled soon.  This will end up breaking the CI/CD pipeline and needs to be addressed.
Info on how to use env files can be found [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
[This is the warning](https://github.com/KinsonDigital/Velaptor/actions/runs/4105239512) displayed in one of the status check logs

### What needs to be done:

**Files that need to be changed are listed below:**
1. build-pr-status-check.yml
2. feature-pr-status-check.yml
3. hotfix-pr-status-check.yml
4. prev-feature-pr-status-check.yml
5. prev-release-pr-status-check.yml
6. prod-release-pr-status-check.yml
7. unit-test-pr-status-check.yml

Each file has a line of code that needs to be changed to upgrade.  Look for all of the lines below and replace them with the new line of code.
> **Warning** Tabs indents are very important in YAML.  Make sure that the new line of code is indented the same amount as the old one that is being replaced.

**What To Change:**
```diff
    - name: Get Pull Request Number
      id: get-pr-number
      run: |
        $pullRequestNumber = "${{ github.ref }}".Replace("refs/pull/", "").Replace("/merge", "");
        Write-Host "Pull Request Number: $pullRequestNumber";
-       Write-Host "::set-output name=pr-number::$pullRequestNumber";
+       "pr-number=$pullRequestNumber" >> $env:GITHUB_OUTPUT;
```

### Acceptance Criteria

- [x] build-pr-status-check.yml
- [x] feature-pr-status-check.yml
- [x] hotfix-pr-status-check.yml
- [x] prev-feature-pr-status-check.yml
- [x] prev-release-pr-status-check.yml
- [x] prod-release-pr-status-check.yml
- [x] unit-test-pr-status-check.yml

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
