### ISSUE TITLE
🚧Fix milestone metadata issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#155]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix the metadata time spent on a single issue text and time calculation.
The release v1.0.0.preview.17 revealed that the text grammar is incorrect as well as the result of the time spent on a single issue.

Do the follow:
1. Change the text from **Most Time Spend On Single Issue:** to **Most Time Spent On Single Issue:**
2. Fix the most time spent calculation
    - Currently it subtracts the issue creation time from the issue closed time.  What it really should be doing is using subtracting the creation time from the closed time of the _**pull request**_ that is attached to the issue.  The pull request is really where the time spent is represented.
      > **Note** This calculation is located in the `MostTimeSpentOnIssue()` extension method.

The issues can be observer [here](https://github.com/KinsonDigital/Velaptor/milestones?state=closed)

<img width="581" alt="image" src="https://user-images.githubusercontent.com/85414302/217829846-578aeb66-a705-40fa-afab-78d9b4c4f67f.png">

### Acceptance Criteria

- [ ] The most time spent text grammar updated
- [ ] The most time spent calculation fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed

**Reason:** This project is not being used anymore
