### ISSUE TITLE
🚧Add ability to allow reverted branches

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#156]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When running status checks on a pull request that is designed to revert another PR that has been merged, the status checks fails due to branch **requirements** returning as failed.  The reason for this is because the default branch name given by GitHub when creating a revert pull request does not adhere to the currently allowed branching syntax.

Add the capability to validate the branch syntax for revert branches that are prefixed with the revert string created by GitHub.

**Original PR Branch Name:** preview/feature/123-my-feature
**Revert Branch For PR Branch Above:** revert-456-preview/feature/123-my-feature

The section `revert-456-` is what is causing the requirements to fail the status check.

**How To Solve**
Create a new NUKE parameters that combined can be used to give the capability to allow revert branches and if `true`, will use use a `string` prefix with globbing patterns that is allowed to be prefixed before the branch.

**Parameters:**
- `AllowBranchReverting:bool`
    - If `true`, this will allow revert PR's for a branch with the normal syntax in addition to the `BranchRevertSyntax` parameter value
- `BranchRevertSyntax:string`
    - This is the prefix syntax of the `string` that is allowed to be prefixed before a valid branch for at PR.

[Here](https://github.com/KinsonDigital/VersionMiner/actions/runs/4145611282/jobs/7170209921) is an example of a status check failing for a revert PR.

### Acceptance Criteria

- [ ] The `AllowBranchReverting` parameter added
- [ ] The `BranchRevertSyntax` parameter added

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
