### ISSUE TITLE
🚧Add ability to skip nuget checks

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#157]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability to skip NuGet package checks.

Do this by adding a new `bool` NUKE parameter that has a default of `true` if not provided.

> **Warning**
> This will have https://github.com/KinsonDigital/CICD/labels/%F0%9F%A7%A8breaking%20changes because currently, there is is no skip capability and NuGet package names and versions are always checked.  Current projects that update to the version of CICD for the release that this issue is contained in, will have to add a parameter value of `true` to the **_parameters.json_** file if the project does NuGet package name/version checks.  This is because the absence of the nuke parameter in the _**parameters.json**_ file will result is a NuGet check of `true`.

The check for the skip value will be checked in the `ThatTheNugetPackageDoesNotExist()` requirement method.

If the NuGet check is set to be skipped, write to the console that it will be skipped. When printing the title of the **requirement**, it uses the `LogRequirementTitle()` extension method.  Replace this method with a new method named `LogSkippedRequirementTitle()` that will print that the message has been skipped with different emojis.  

**Use the skip message below:**
- ⬜ Requirement '<requirement-name>' Skipped ⬜

### Acceptance Criteria

- [x] Skip NuGet checks parameter added
    - [x] The name of the parameter should be `SkipNuGetChecks`
- [x] Requirement title updated to show skips
- [x] If the NuGet check is skipped, log the skip to the console.
- [x] Create issues for all projects that use CICD to update the _**parameters.json**_
  > **Note** Use this [search link](https://github.com/search?q=org%3AKinsonDigital+path%3A**%2Fparameters.json&type=code) to find all projects that contain the file for update.
### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
