### ISSUE TITLE
🚧Fix logging issue with preview release PR status check

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#158]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix an issue with preview release PR status checks where the **ThatThePRBranchIsValid** requirement is logging the error incorrectly.  The error is stating that the pull request is an invalid master branch when it should say that it is an invalid preview feature branch.

Go [here](https://github.com/KinsonDigital/VersionMiner/actions/runs/4146534496/jobs/7172309315) for a real world example of the failure.

### Acceptance Criteria

- [ ] The log message is fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
