### ISSUE TITLE
🚧Change how release note paths work

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#17]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the location of release notes is located in the `Documentation` folder.  There is also a hard-coded release notes dir name field named `ReleaseNotesDirName`.  The field is used to construct the dir path of where the release notes are located.  This path construction **depends** on the documentation dir path to get access to the release notes for some of the NUKE targets.

There is also a static property of type `AbsolutePath` that is the directory path of where the release notes are located.  Convert this property to a NUKE parameter.  This is going to mean that the path could possibly not be set up in the `~.nuke/parameters.json` file which means that it will be null or empty when the target is executed.  So the targets that use this new NUKE param property will have to check if it is null or empty.

Create a `Requires()` method that can be used to check that the release notes dir path is not null or empty.  This is just in case something went wrong in the path construction.  Find all of the targets that use the release notes pathing and setup a requires that use the new method to check.

Convert the static prop `ReleaseNotesBaseDirPath` to a NUKE parameter.  This will be the base path of where the preview and production releases will live.

### Acceptance Criteria

- [x] New NUKE param prop named `PreviewReleaseNotesDirName` created
- [x] New NUKE param prop named `ProductionReleaseNotesDirName` created
- [x] The static prop `ReleaseNotesBaseDirPath` is converted to a NUKE param
  - This is the location where the preview and production release note directories will reside
- [x] `PreviewReleaseNotesDirPath` prop refactored to not be static and to use the `ReleaseNotesBaseDirPath` and `PreviewReleaseNotesDirName` properties to construct the path.
  - This will use the new `PreviewReleaseDirName` to construct the path
- [x] `ProductionReleaseNotesDirPath` prop refactored to not be static and to use the `ReleaseNotesBaseDirPath` and `ProductionReleaseNotesDirName` properties to construct the path.
- [x] ~Targets that require the release notes using the new `Requires()` methods to check for null or empty.~

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Did not implement the AC item below.
- [x] ~Targets that require the release notes using the new `Requires()` methods to check for null or empty.~

**Reason:**  After implementing the functionality for the release notes paths, the default values will never have these NUKE params as empty or null.  They all have default values so checking if they are null or empty is not necessary.
