### ISSUE TITLE
🚧Update workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#179]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update various pieces of the workflow to avoid deprecation issues with **Nodejs** and the **set-output** workflow command.

1. Update the `Validate_Version>Get Version From Project File` step in the _**preview-release.yml**_ file to use the latest version of _**VersionMiner**_.
2. Update the `Validate_Release_Notes_Exist>Get Version From Project File` step in the _**preview-release.yml**_ file to use the latest version of _**VersionMiner**_.
3. Update the `actions/setup-dotnet` actions from version _**v1**_ to _**v3**_
4. Update the `actions/setup-nuget` action from version _**v1.0.5**_ to **_v1_**.
    > **Note** This will let the action use the latest minor and/or patch version.
5. Replace all deprecated usages of the `::set-output` workflow command with the new step output syntax.
    > **Note** Example of a replacement 👉🏻 `"sdk-version=${{ env.NET_SDK_VERSION }}" >> $env:GITHUB_OUTPUT;`

### Acceptance Criteria

- [ ] `Validate_Version>Get Version From Project File` step in the _**preview-release.yml**_ file updated to use the latest version of _**VersionMiner**_.
- [ ] `Validate_Release_Notes_Exist>Get Version From Project File` step in the _**preview-release.yml**_ file updated to use the latest version of _**VersionMiner**_.
- [ ] `actions/setup-dotnet` actions updated from version _**v1**_ to _**v3**_
- [ ] `actions/setup-nuget` action updated from version _**v1.0.5**_ to **_v1_**.
- [ ] All deprecated usages of the `::set-output` workflow command replaced with the new step output syntax

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
