### ISSUE TITLE
🚧Change how README is transformed

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#180]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, when a project is doing a release, the release notes are checked to be able to automate the process of refactoring the README before packing the release notes into the NuGet package.  

The reason this is done is because the readme file contains HTML that is valid and used in GitHub, but not in nuget.org.  This is why the process is ran.

The current refactor process is causing issues with the team members being able to quickly understand and properly deal with the special syntax in the readme that the translator requires.  To fix this, the idea is that the translator will not require special _**markers**_ in the readme to commend and uncomment blocks.

Instead, it will search for each type of GitHub flavor of HTML and/or markdown and then automatically just translate it to the nuget.org flavor of markdown.

This will greatly reduce the maintenance and complexity of the README files.

### Acceptance Criteria

- [x] README translator changes working

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
