### ISSUE TITLE
🚧Update using directive locations

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#183]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Adjust the positioning of all the using directives throughout the code base to follow the projects coding standards.

The warning produced by this upon build is the _**SA1200**_ warning with the description of _**Using directive should appear within a namespace declaration.**_

This simply requires that the namespace declaration is above the using statements.  Refer to example shown below.

```diff
+ namespace CICDSystem.Services;

using System.Diagnostics.CodeAnalysis;
using System.IO;
using CICDSystem.Services.Interfaces;
using Nuke.Common.Git;

- namespace CICDSystem.Services;
```

### Acceptance Criteria

- [ ] All using directive positions adjusted.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:** Project is not used anymore.
