### ISSUE TITLE
🚧Improve GitHubClient setup and usage

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#19]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the `GitHubClient` setup and usage throughout the project. 

Currently, the setup of the `GitHubClient` is not ideal when trying to make authorized GitHub API requests when running targets that use the GitHub API.   To try and solve this issue, the `LoadSecrestService` was created to load a token to be used for setting up the `GitHubClient` for authorized requests.  This needs to be put into use.

Create a new service called `GitHubClientService` that is used to create a `GitHubClient` object that is set up with a token for authorized requests.  The new `GitHubClientService` will inject and use the `LoadSecretsService` to load the token from the disk.

The `GitHubClientService` and `LoadSecretsService` should also be set up with _**SimpleInjector**_ so they can be easily consumed.  The `GitHubClientService` should be set up in the IoC container as a singleton.

The `GitHubClient` property will be a `readonly` property that uses the `GitHubClientService` every time it is requested.  The service will lazy load/create the internal client object/field.  Every subsequent request into the service will check if the field is null and if it is not, simply return a reference of the field.

### Acceptance Criteria

- [x] `LoadSecretsService` changes
  - [x] Create an interface for the service for setup for the IoC container
  - [x] Refactor the main implementation code to be able to use `System.IO.Abstractions`
  - [x] Create unit tests for the `LoadSecretsService` class
- [x] Create new `GitHubClientService` service
- [x] Convert the `GitHubClient` from a `private static` field to a `private` property with a getter
  - The getter will call out to the `GitHubClientService` service to get the client
- [x] `LoadSecretsService` name refactored to `SecretService`
  - [x] Refactor all `var` and `param` names to appropriate names
- [x] If the loaded secret is null or empty, throw an exception

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
