### ISSUE TITLE
🚧Update action in preview release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#191]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the **_KinsonDigital/VersionValidator_** action from version **_v1.0.0-preivew.2_** to _**v1.0.0-preview.4**_ in the _**preview-release.yml**_ workflow file.

```diff
    - name: Validate Version
-     uses: KinsonDigital/VersionValidator@v1.0.0-preview.2
+     uses: KinsonDigital/VersionValidator@v1.0.0-preview.4
      with:
        nuget-package-name: "KinsonDigital.${{ env.PROJECT_NAME }}"
        version: "${{ needs.get_version.outputs.version }}"
        check-nuget: "true"
        fail-if-nuget-version-exists: "true"
```

### Acceptance Criteria

- [x] Action in workflow updated to latest version

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
