### ISSUE TITLE
🚧Update tweet service

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#199]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the `TwitterService` to use v2.0 of the Twitter developer API.  v1.1 has been deprecated.
The service used to use the TwitterTask that came with NUKE but this is causing issues due to it still using the now deprecated v1.1 version of the API.

Update the URL `https://api.twitter.com/1.1/statuses/update.json` to `https://api.twitter.com/2/tweets` in the `TwitterService` class

### Acceptance Criteria

- [x] URL updated in service
- [x] Full testing performed and tweet is being sent out successfully

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
