### ISSUE TITLE
🚧Update NUKE nuget package

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#203]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the NUKE NuGet package from _**v6.3.0**_ to the latest version as of when this issue is worked on.

The latest version when this issue was created was _**v7.0.0**_.

Make sure to build the project using Visual Studio to see if everything builds ok.

### Acceptance Criteria

- [x] **Nuke.Common** updated to the latest version.
- [x] Solution builds correctly
- [x] All unit tests pass

> **Note** Ask @CalvinWilkinson for assistance on how to build the solution and run unit tests in VS.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
