### ISSUE TITLE
🚧Refactor classes to internal and/or sealed

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#26]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

This is a build tool.  Not a library meant for anybody to use to solve build problems.  It is currently only for the **KinsonDigital** organization.  Due to this, the code should be more hidden and closed off.

If the need arises in the future to expose or unseal anything for extension, it can be done then.

If the class can be internal, make it internal.
All classes should be sealed unless any inheritance is going on.  But I do not think that is going on.

### Acceptance Criteria

- [x] All classes that should be `internal`, is set to `internal`
- [x] All classes that are not `sealed` should be set to `sealed`.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
