### ISSUE TITLE
🚧Create new solution service

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#27]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a new service to wrap up all of the NUKE solution functionality that is currently being used.  This will help increase testability which will eventually enable tests to be written for the build system.

The service is going to require an instance of the `Solution` from NUKE to exist inside the service so the service can do its job.

**Things To Consider:**
1. Currently there is no way to manually create a `Solution (NUKE)` object manually like the `GitRepository (NUKE)` object.
    - This means that we need to find a way to get the solution object inside of the service.  One way is to create an observable.
    - The service will be very light weight like a thin wrapper.

### Acceptance Criteria

- [x] `SolutionService` created
- [x] Service added to IoC container
- [x] Create the required `Reactable`'s to be used to get the **_NUKE_** `Solution` object into the service
- [x] Code refactored to use service

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
