### ISSUE TITLE
🚧Fix GitHub token service issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#33]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently the `GitHubTokenService` is not working correctly.  The token service uses the `SecretService` to load the GitHub token locally from disk when running locally.  The issue is that the `SecretService` is looking in the wrong location.  

**How it is supposed to work:**
It is supposed to look inside of the _**.github**_ folder in the root of the repository.  If the folder directory path exists, it should check for the `local-secrets.json` file and load the token from the file.

**How it currently working:**
It uses the _**.github**_ folder as part of the path, but the section before the _**.github**_ folder in the path is incorrect.  It is building the beginning section of the path based on the execution path of the assembly.  This is how it was originally designed, but the ⚽ was dropped and somebody forgot to update the service.   (That somebody was "me". 😁

**How To Fix It:**
Instead of using the executable assembly, use the `Directory.GetCurrentDirectory()` instead to build the path section before the _**.github**_ folder.  This represents the root of the repository.  The `SecretService` uses the `ICurrentDirService` to be able to get the executing assembly.  This is only used in the `SecretService` class.  Just delete the `ICurrentDirService` interface and `CurrentDirService` class entirely.  It is not needed anymore.

### Acceptance Criteria

- [ ] Refactor the `SecretService` to build the path correctly.
- [ ] `SecretService` unit tests updated
- [ ] `ICurrentDireService` interface deleted
- [ ] `CurrentDireService` class deleted

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
https://github.com/KinsonDigital/CICD/labels/%F0%9F%A7%A8breaking%20changes introduced.

The `BuildSettingsDirPath` (CLI switch `--build-settings-dir-path`) had been renamed to `WorkflowTemplateOutput` (CLI switch `--workflow-template-output`)

**Comment by CalvinWilkinson** [comment]
https://github.com/KinsonDigital/CICD/labels/%E2%9C%A8new%20feature introduced.

Added descriptions to all of the build parameters.  These will show up in the CLI when using `dotnet cicd --help`
