### ISSUE TITLE
🚧Create app icon and proj logo

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#36]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a project logo. This logo should be the same as the KinsonDigital logo, but instead of **{ KD }** in between the braces, add an up arrow in the center which represents shipping code/releases, and rotation arrows around the outside of the gear.

You could also put the arrows inside of the gear if there is room.

Once this is figured out, convert this into an application icon.

**NuGet Setup:**
Set up the NuGet package to use the icon. Make sure that the NuGet icon is packed into the package.

**README:**
Update the `README.md` file by adding the logo to the center and at the top

### Acceptance Criteria

- [x] Logo created
- [x] Logo added to `README.md` file
- [x] Application Icon set
  - This is the `<ApplicationIcon/>` element
- [x] Icon
  - [x] Added to project
  - [x] Added to NuGet package
  - [x] Package Icon set
    - This is the `PackageIcon/>`
  - [x] Setup in csproj file

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
