### ISSUE TITLE
🚧Template workflow generation issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#41]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When generating the workflow templates using the `dotnet cicd GenerateWorkflows` command, the `unit-test-status-check.yml` workflow template is not getting generated.

No errors are being thrown at all.  It just simply is not working.  The only theory I have is that the templates are being generated file by file alphabetically and this file is the last file.  The file is probably somehow just being skipped due to the premature ending of the code.

### Acceptance Criteria

- [ ] `unit-test-status-check.yml` workflow template is generated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without doing work.

**Reason:**
This was fixed with one of the issues in release [v1.0.0-preview.8](https://github.com/KinsonDigital/CICD/milestone/8?closed=1)
