### ISSUE TITLE
🚧Handle GitHubActionsService issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#42]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

An error is thrown when trying to get the pull request number for a target when the run is not a pull request run.

[Here](https://github.com/KinsonDigital/CICDTest/actions/runs/3155044290/jobs/5133302995) is the link to the _**CICDTest**_ to the `🪲Debuggin Workflow` run of when the error occurred.

**Error Screenshot:**
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/85414302/193155974-c21d8fd6-9da3-43f8-893a-bc832207af0f.png">

---

**More Information:**
In the `GitHubActionsService` class, the `PullRequestNumber` property gets the pull request number from either the pull request number value sent in via the CLI during local builds or from the `GitHubActions.Instance.PullRequestNumber` property during server builds.

The problem is when running a server run that is not a pull request.  For example, manual execution using the `workflow_dispatch` event.  Because the run is not a pull request run, their is no pull request data available.  Internally in the property, NUKE is using `JObject` to get the pull request data from some JSON data.  But since that data is not available, it explodes.  💥

To fix this, make a change in the `GitHubActionsService.PullRequestNumber` property.  Just first check to see if the build is a server build.  If so, use the `GitHubActions.Instance.PullRequestNumber` value.  If not, return null.

### Acceptance Criteria

- [x] Bug fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
