### ISSUE TITLE
🚧Pull request is 0 error

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#43]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When running a pull request build on the server, the build status check target is reporting that the pull request number is 0.  This is not the case.

This is occurring in the `ThatThePullRquestExists()` requirement method.  Further investigation shows that the logic in this method is incorrect and needs to be changed.  Currently it checks the local build `PullRequestNumber` build parameter value _**AND**_ is using this value to check if the pull request exists as long as the value of it is not 0.

This will not work because the `PullRequestNumber` is only for local builds, and is always 0 with server builds. This means the result is always 0 so it fails.  Basically, this method is only setup for local builds, not local _**AND**_ server builds.

Rewrite the method to work for both occasions.

---

### **Other Info:**

[Here](https://github.com/KinsonDigital/CICDTest/actions/runs/3155115995/jobs/5133450380) is the link to the `🪲Debugging Workflow` action run where the bug occurred.

**File CICD.Requirements.cs**
```cs
 private bool ThatThePullRequestExists()
    {
        nameof(ThatThePullRequestExists)
            .LogRequirementTitle("Checking if the pull request number exists.");
                               👇🏼This line here is the problem.👇🏼
        var result = PullRequestNumber != 0 && GitHubClient.PullRequest.Exists(RepoOwner, RepoName, PullRequestNumber).Result;

        if (result)
        {
            Console.WriteLine($"{Environment.NewLine}{ConsoleTab}The pull request number '{PullRequestNumber}' exists.");
            return true;
        }

        Log.Error($"The pull request number '{PullRequestNumber}' does not exist.");
        Assert.Fail("Pull request failure.");
        return false;
    }
```

### Acceptance Criteria

- [x] Requirement method rewritten to work for server builds.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
