### ISSUE TITLE
🚧Create unit tests for extension methods

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#52]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create unit tests for the following extension methods:

- `IssueExists()`
- `HasLabels()` for pull requests client
- `Exists()`
- ~~`LabelExists()`~~
- `IsAssigned()`
- `HasLabels()` for issues client

### Acceptance Criteria

- [x] Unit tests created for the following methods:
  - [x] `IssueExists()` method unit tests created
  - [x] `HasLabels()` method unit tests created for the pull requests client overload
  - [x] `Exists()` method unit tests created
  - [x] ~~`LabelExists()` method unit tests created~~
  - [x] `IsAssigned()` method unit tests created
  - [x] `HasLabels()` method unit tests created for the issues client overload

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
