### ISSUE TITLE
🚧Create unit tests for extension methods

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#53]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create unit tests for the following extension methods:

`ReleaseExists()`
`MilestoneExists()`
`GetByTitle()`
`GetHtmlUrl()`
`CloseMilestone()`
`UpdateMilestoneDescription()`
`UploadTextFileAsset()`
`GetLogText()` - This is overloaded.  Create tests for both.

### Acceptance Criteria

- [x] Unit tests created for the following methods:
  - [x] `ReleaseExists()` method unit tests created
  - [x] `MilestoneExists()` method unit tests created
  - [x] `GetByTitle()` method unit tests created
  - [x] `GetHtmlUrl()` method unit tests created
  - [x] `CloseMilestone()` method unit tests created
  - [x] `UpdateMilestoneDescription()` method unit tests created
  - [x] ~`UploadTextFileAsset()` method unit tests created~
  - [x] `GetLogText()` method unit tests created for both overloads

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Did not create unit tests for the `UploadTextFileAsset()` method.

**Reason:** This is because it does file operations using the `System.IO.File` class.  This is not ideal for testing unless they are abstracted away using `System.IO.Abstractions` NuGet package.

This will eventually make it into a milestone service for the issue below:
- #74
