### ISSUE TITLE
🚧Create branch validator service

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#60]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a new service called `BranchValidatorService`.  This new service will provide everything related to validating branches.  This will check if a branch has valid syntax, check if an issue number in a branch exists, check if the branch is a correct branch type using a delegate, etc.

**Reason:**
Implementing this will greatly improve testability as well as flexibility.  If the branching model needs to be changed, then this can happen.

This service will need to inject whatever is required for it to do its job.  Also, this should be a fluent API with OR and AND logic.
This means that there should be 2 methods named `And()` and `Or()`.

There also should be a `Reset()` method that resets the state of everything for service reuse.  Since the service will be a singleton, this means that the state can carry over.  Implement a `GetResult()` method to return the result of the validation process.
The service needs to reset its validation state internally when the `GetResult()` method is called.  This will make sure that the state is not carried over to other parts of the build system when it is reused.

**And Or Logic Implementation:**
This should be accomplished by having 2 arrays in the service. 
Fist Array (AND list): One array will hold a list of bool values that will be _**ANDED**_ together.
Second Array (OR list): The second array will consist of a list of bool lists.  Each item will be a list of `bool`s.  Every time `Or()` is invoked, the current **_AND_** snapshot of bool items will be copied to the **_OR_** list and the **_AND_** list will be cleared out.  Once `GetValue()` is invoked, the **_OR_** list can be processed to get an end result of type `bool` the entire process.

⚠️This logic will have to be thoroughly tested!!

Go through the code base and look for this validating type functionality and implement it into the new service.
Once it is all finished, the code throughout the project can be refactored to use the new validator service.

A great place to look for this kind of required validation is in the `ExtensionsMethods.cs` file.

### Acceptance Criteria

- [x] Service Created
  - [x] `Or()` method implemented
  - [x] `GetValue()` method implemented
  - [x] Fluent API implemented throughout
  - [x] Units test thoroughly test implementation and all pass

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
