### ISSUE TITLE
🚧Issue with detecting open milestone pull requests

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#67]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When detecting open pull requests in a milestone and when the detection should skip _**release todo issues & pull requests**_, the issue or pull request is detected anyways when it should not.  This is a simple fix.  The boolean value and comparison logic should be changed to the setup below.

**`ThatAllOfTheReleaseMilestoneIssuesAreClosed()` Requirement Method:**
```diff
        var openMilestoneIssues = GitHubClient.Issue.IssuesForMilestone(RepoOwner, RepoName, projectVersion)
            .Result
-            .Where(i => (skipReleaseToDoIssues || i.IsReleaseToDoIssue(releaseType)) && i.State == ItemState.Open).ToArray();
+            .Where(i => (skipReleaseToDoIssues is false && i.IsReleaseToDoIssue(releaseType)) && i.State == ItemState.Open).ToArray();
```

**`ThatAllOfTheReleaseMilestonePullRequestsAreClosed() Requirement Method:`**
```diff
        var openMilestonePullRequests = GitHubClient.Issue.PullRequestsForMilestone(RepoOwner, RepoName, $"v{projectVersion}")
            .Result
-            .Where(i => (skipReleaseToDoPullRequests || i.IsReleasePullRequest(releaseType)) && i.State == ItemState.Open).ToArray();
+            .Where(i => (skipReleaseToDoPullRequests is false && i.IsReleasePullRequest(releaseType)) && i.State == ItemState.Open).ToArray();
```

### Acceptance Criteria

- [x] `ThatAllOfTheReleaseMilestoneIssuesAreClosed()` requirement method fixed
- [x] `ThatAllOfTheReleaseMilestonePullRequestsAreClosed()` requirement method fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
