### ISSUE TITLE
🚧Non existing nuget not handled correctly

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#69]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

If the NuGet package does not exist because it has never been pushed to _**nuget.org**_, an HTTP status code of 404 (Not Found) will be thrown.  This displays an obscure XML error that comes with the NuGet API when a package is not found.

Instead, add a try-catch that can check if the 404 error exists, and if so, simply return true.

This exists in the requirement method `ThatTheNugetPackageDoesNotExist()`.

**Changes To Implement:** 
```diff
        var projectVersion = project.GetVersion();

        var nugetService = new NugetDataService();
+       var packageVersions = Array.Empty<string>();

-       var packageVersions = nugetService.GetNugetVersions(RepoName).Result;
+       try
+       {
+           packageVersions = nugetService.GetNugetVersions("CICDTest").Result;
+       }
+       catch (HttpRequestException e)
+       {
+           if (e.StatusCode == HttpStatusCode.NotFound)
+           {
+               return true;
+           }
+       }

        var nugetPackageExists = packageVersions.Any(i => i == projectVersion);
```

### Acceptance Criteria

- [x] Try catch block added to look for 404 (Not Found) in the requirement method.
- [x] Testing in _**CICDTest**_ complete and working

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
