### ISSUE TITLE
🚧Create milestone service

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#74]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a new service named `MilestoneService`.  This service will contain all of the required functionality that is required for milestones.  This can all be found throughout the code base using the `Octokit` methods as well as all of the extension methods for the `IMilestonesClient` interface.

Build the service to provide all of the functionality that is used throughout the project.  Unit tests should be created as well and all code should be refactored to use the service.

Also, the repo owner and name are required for a lot of this functionality due to the `Octokit` API.  The service should have an `IReactable<(string, string)>` injected via the ctor so it can get the repo owner and name information for it to do its job.

### Acceptance Criteria

- [ ] New service with the named `MilestoneService` created.
- [ ] Repo info reachable injected into the service for use.
- [ ] Unit tests created for the entire service

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [ ] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed

**Reason:** This is not being used anymore
