### ISSUE TITLE
🚧Fix simple logging issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#78]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

In the `ThatFeaturePRIssueHasLabel()` requirement method, the main requirement method title and description are not properly printed to the console log.

Currently, it logs the name of the requirement method, which is correct.  But the description of what the requirement method does is not correct.

**Change To:**
```diff
- .LogRequirementTitle($"Checking that the issue number in the '{branchTypeStr}' branch exists.");
+ .LogRequirementTitle($"Checking that the issue for the '{branchTypeStr}' branch contains at least one label.");
```

### Acceptance Criteria

- [x] Requirement method title and description logged to console has been fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
