### ISSUE TITLE
🔬Research GraphGL API for future use

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#79]
### Complete The Item Below

- [X] I have updated the title without removing the 🔬 emoji.

### What To Research

Research how GraphQL works and how to use it.  This is for the purpose of future enhancements on dealing with GitHub data and can help enhance the CICD project itself.

**Resources:**
- [GraphQL Org](https://graphql.org/)
- [GitHub GraphQL API](https://docs.github.com/en/graphql)

Create some examples that can be documented into this issue.  Also try to use GraphQL in postman which will not only help learn about GraphQL, but also about using the GitHub GraphQL API.

Once this is all done and understood, create some issues to use the GraphQL API to add a feature to interact with the new project system to check if an issue or PR has been added to the project as well as possibly check which column it is in.

Another benefit is that once GraphQL is understood, workflows can be created to help automate some of the board flow.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Research complete and issues created _(if needed)_.
- [ ] If any issues were created, they have been added to the _**Related Work**_ section below.

### ToDo Items

- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct project.

### Additional Information:

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
