### ISSUE TITLE
🚧dotnet tool enhancements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#8]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Se tup the project to properly be used as a dotnet tool.  This will allow the project to be used for CICD operations easily as a dotnet tool by the rest of the organization's projects.

### Acceptance Criteria

- [x] Project properly setup as a dotnet tool
- [x] Able to run a target to generate all of the required workflows
- [x] Test project with unit tests created and setup to use the CICD project as a dotnet tool

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
