### ISSUE TITLE
🚧Exception thrown for preview releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#81]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

An exception is being thrown for the preview release target only for server runs.

This only occurs when getting the configuration for running unit tests and builds.  This is due to how the branch is being detected when deciding if the build or test execution should be a _**Debug**_ or _**Release**_ run.

The exception is a _**Octokit**_ `NotFoundException`.  This is because the branch being used for configuration detection is the target branch of a pull request.  The problem is that preview and production releases do not run off of a pull request event.  They are executed manually.  Due to this, the pull request number is 0 and this is the number used when trying to pull PR information using the GitHub API when using _**Octokit**_.

This fortunately is an easy fix.  Refer to the fix below.

Located in the `GetBuildConfig()` method in the `CICD.cs` file.
```diff
- return PullRequestService.TargetBranch.IsMasterBranch()
+ return Repo.Branch.IsMasterBranch()
            ? Configuration.Release
            : Configuration.Debug;
```

This fix uses the repository service to figure out the currently checked-out branch instead of the pull request service which reaches out to GitHub to get PR data.

### Acceptance Criteria

- [x] Bug fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
