### ISSUE TITLE
🚧Fix issue with creating milestone description

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#86]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, there is only one method to create the custom milestone description for preview and production releases.

The name of the method implies that it is only for production but it's implementation actually only is for preview.  This needs to be fixed.  Also, the implementation needs to be improved and refactored to be used for both.

To do this, add a `ReleaseType` parameter to the method and dynamically perform what is required based on this param value.
Once finished, the method also needs to be used in the preview release target.

### Acceptance Criteria

- [x] The `GetProdMilestoneDescription()` method renamed to `CreateMilestoneDescription()`
- [x] Parameter of type `ReleaseType` added to the method
- [x] Method refactored for better variables names as well as to work for both types of releases

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
