### ISSUE TITLE
🚧Fix release note title logging issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#90]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When checking the title of production release notes during a production PR status check run, the content logged to the console about the incorrect title is incorrect.

The issue is that the error log stated that it was looking for a preview release notes title but it should have stated that it was looking for a production release notes title.

This issue resides in the requirement method named `ThatTheReleaseNotesTitleIsCorrect()`.
This issue was discovered when running a _**Production Release PR Status Check**_.  Refer to the action run [here](https://github.com/KinsonDigital/CICDTest/actions/runs/3236256166/jobs/5301813830).

**The Current Incorrect Log Message:**
```console
Error: A release notes title with the syntax '<project-name> <release-type> Release Notes - v#.#.#-preview.#' could not be found.
	       Expected Title: CICDTest Production Release Notes - v1.0.0
```

**Message Should Of Been:**
```console
Error: A release notes title with the syntax '<project-name> <release-type> Release Notes - v#.#.#' could not be found.
	       Expected Title: CICDTest Production Release Notes - v1.0.0
```

### Acceptance Criteria

- [x] Logging issue fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
