### ISSUE TITLE
🚧Fix release notes validation logging issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#91]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When validating the content of the release notes, the error msg logged to the console is incorrect.

This error message is related to when the **_production release_** notes do not have any preview release items in the **_preview release_** section of the **_production release notes_**.  This validation is only checked if any preview releases even exist for a **_production release_**.

**Current Log Issue:**
![image](https://user-images.githubusercontent.com/85414302/195402828-9c6650b5-0eb4-43b3-98ae-a47dbb3470d6.png)

This can be found [here](https://github.com/KinsonDigital/CICDTest/actions/runs/3236401309/jobs/5302157345)

---

**How To Fix:**
This is found in the requirement method named `ThatTheProdReleaseNotesContainsPreviewReleaseItems()`.

```diff
-        nameof(ThatTheProdReleaseNotesContainsPreviewReleaseSection)
+        nameof(ThatTheProdReleaseNotesContainsPreviewReleaseItems)
            .LogRequirementTitle($"Checking if the 'production' release notes contains a preview releases section if required.");
```

### Acceptance Criteria

- [x] Simple requirement method logging of title and message fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
