### ISSUE TITLE
🚧Simple logging adjustment

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#92]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When `ThatTheProdReleaseNotesContainsPreviewReleaseSection()` requirement method is executing, the logging message of the result needs to be adjusted.  It currently has a _**SeriLog**_ prefix on it and it needs to be removed.

This issue can be seen in the action run [here](https://github.com/KinsonDigital/CICDTest/actions/runs/3236401309/jobs/5302157345)

**Screenshot Of Fix:**
![image](https://user-images.githubusercontent.com/85414302/195404100-d592357a-22f4-42eb-a609-5241b1d7cb67.png)

---

**How To Fix:**
Fix this in the `ThatTheProdReleaseNotesContainsPreviewReleaseSection()` requirement method.

```diff
        if (errors.Count <= 0)
        {
-           var logMsg = $"The production release '{prodVersion}' does not have any previous preview releases.";
+           var logMsg = $"{ConsoleTab}The production release '{prodVersion}' does not have any previous preview releases."; 
            logMsg += $"{Environment.NewLine}{ConsoleTab}Release notes check for preview release items complete.";
-           Log.Information(logMsg);
+           Console.WriteLine(logMsg);
            return true;
        }
```

### Acceptance Criteria

- [x] Logging issue fixed
- [x] Requirement method refactored to improve code _(if applicable)_

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
