### ISSUE TITLE
🚧Change milestone description

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#93]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Make a simple change to the creation of the milestone descriptions by changing the summary titles to singular instead of plural.

The production milestone summary value is _**Production Releases**_ and should be _**Production Release**_
The preview milestone summary value is _**Preview Releases**_ and should be _**Preview Release**_

**Example:**
![image](https://user-images.githubusercontent.com/85414302/195415914-ae574b7c-71c6-42a8-af5a-87a774929e0d.png)

---

**How To Fix:**
This is located inside of the `CreateMilestoneDescription()` method in the `CICD.Common.cs` file.

```diff
- var detailsStartTag = $"<details closed><summary>{releaseTypeStr} Releases</summary>{Environment.NewLine}";
+ var detailsStartTag = $"<details closed><summary>{releaseTypeStr} Release</summary>{Environment.NewLine}";
const string detailsEndTag = "</details>";
```

### Acceptance Criteria

- [x] Description fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
