### ISSUE TITLE
🚧Fix logging issue with milestone assignment check

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#94]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When the requirement method named `ThatThePRIsAssignedToMilestone()` is executing, it is incorrectly logging its title and description to the console.

Fix this issue by simply updating the method name included in the title.

**Refer to fix below:**
Located in the `CICD.Requirements.cs` file in the `ThatThePRIsAssignedToMilestone()` method.

```diff
-        nameof(ThatAllMilestonePullRequestsHaveLabels)
+       nameof(ThatThePRIsAssignedToMilestone)
            .LogRequirementTitle("Checking that the pull request is assigned to a milestone.");
```

Also fix the other logging issue inside the same requirement method.

**Refer to fix below:**
```diff
        if (isAssigned)
        {
            var title = milestone?.Title ?? string.Empty;
-            Console.Write($"{Environment.NewLine}The pull request '{PullRequestNumber}' is assigned to milestone '{title}'.");
+           Console.WriteLine($"{Environment.NewLine}{ConsoleTab}The pull request '{PullRequestNumber}' is assigned to milestone '{title}'.");
            return true;
        }
```

### Acceptance Criteria

- [x] Logging issues fixed

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
