### ISSUE TITLE
🚧Fix requirement issue with hotfix pr status checks

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#95]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the `HotFixPRStatusCheck` target contains a requirement method named `ThatPreviewFeatureIssueNumberExists()` that should not be there.  This is only for preview features.

~This needs to be replaced with a similar requirement method with the name `ThatHotFixIssueNumberExists()`.
This requirement method does not exist so it will have to be created.~

This needs to be refactored to work with all issue number branches.  The branch is pulled from the source branch of the pull request.  If the branch is not an issue number type branch, then the requirement will fail.

```diff
    private Target HotFixPRStatusCheck => _ => _
        .Requires(
            () => ThatPullRequestNumberIsProvided(),
            () => ThatThePullRequestExists(),
            () => ThatThePRBranchIsValid(PRBranchContext.Source, BranchType.HotFix),
            () => ThatThePRBranchIsValid(PRBranchContext.Target, BranchType.Master),
            () => ThatThePRIsAssignedToMilestone(),
-            () => ThatPreviewFeatureIssueNumberExists(),
+           () => ThatThePRSourceBranchIssueNumberExists(),
            () => ThatFeaturePRIssueHasLabel(BranchType.HotFix),
            () => ThatThePRHasBeenAssigned(),
            () => ThatPRHasLabels());

```

### Acceptance Criteria

- [x] Current requirement method named `ThatPreviewFeatureIssueNumberExists()` refactored to work properly

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
