### ISSUE TITLE
🚧Requirements added to hotfix pr status check target

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/CICD#96]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, the requirements for the _**HotFixPRStatusCheck**_ target is very minimal.  Since hotfix features are a combination of a feature and a release all rolled into one, it requires more checks as a production PR status check does.

Use the _**ProdReleasePRStatusCheck**_ target as a guide to help add more requirement checks to the _**HotFixPRStatusCheck**_ target.

### Acceptance Criteria

- [x] More requirements added to the _**HotFixPRStatusCheck**_ target

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [x] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| Workflow Changes    | `workflow` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
